version: "3.6"

services:
  hyperledger-updates:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hyperledger-updates
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - ./html/generated:/app/html/generated
      - ./generated-data:/app/generated-data
